### ISSUE TITLE
Recent deploy causes PHP Fatal Error

### ISSUE THREAD

**Issue by tbutterf** [webflo/drupal-finder#67]
The [Drastically simplify using Composer Runtime API (](https://github.com/webflo/drupal-finder/commit/1fa65484857c7a2e4dcf0d9e0b47198fe0681b8a)https://github.com/webflo/drupal-finder/pull/65[)](https://github.com/webflo/drupal-finder/commit/1fa65484857c7a2e4dcf0d9e0b47198fe0681b8a) commit deployed to master yesterday is causing problems on Drupal 10 sites. Composer builds properly, but when I try to run a Drush command, such as a cache-rebuild, I get the following error:
`PHP Fatal error:  Uncaught TypeError: is_link(): Argument #1 ($filename) must be of type string, Drush\Config\Environment given in /var/www/html/vendor/webflo/drupal-finder/src/DrupalFinder.php:153
Stack trace:
#0 /var/www/html/vendor/webflo/drupal-finder/src/DrupalFinder.php(153): is_link(Object(Drush\Config\Environment))
#1 /var/www/html/vendor/webflo/drupal-finder/src/DrupalFinder.php(75): DrupalFinder\DrupalFinder->discoverRoots(Object(Drush\Config\Environment))
#2 /var/www/html/vendor/drush/drush/src/Preflight/Preflight.php(310): DrupalFinder\DrupalFinder->__construct(Object(Drush\Config\Environment))
#3 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(58): Drush\Preflight\Preflight->preflight(Array)
#4 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run(Array)
#6 /var/www/html/vendor/drush/drush/drush(4): require('/var/www/html/v...')
#7 /var/www/html/vendor/bin/drush(119): include('/var/www/html/v...')
#8 {main}
  thrown in /var/www/html/vendor/webflo/drupal-finder/src/DrupalFinder.php on line 153`

**Comment by tbutterf** [comment]
It looks like updating Drush to the latest supported version solves this issue.

**Comment by tbutterf** [comment]
However, sometimes updating Drush to the latest isn't possible or advisable. If a site is on Drupal 9, it can't run the latest Drush version. I still think this needs to be solved in this package.

**Comment by FraserThompson** [comment]
We were experiencing this with Drush 12.4.3 and updating to the latest 12.x (12.5.2) fixed it. However as noted above, Drush 12.x isn't compatible with Drupal 9, so this workaround won't work for Drupal <10.

**Comment by tbutterf** [comment]
I did some more testing in Drupal 9 with Drush 11.x, and it looks like Drush 11.x isn't affected by this issue. So, maybe nothing needs to be done?
